### PR TITLE
upgrade to current geotools (22.1)

### PR DESCRIPTION
**Pull request by stevenleadbeater**
All tests are passing and I have loaded the jars from the zip file to a geoserver war for current geoserver and added a neo4j data source without errors being thrown

### CODE REVIEW

**Comment by mprins** [comment]
:+1: 

you might want to change "oraclejdk8" in 

https://github.com/neo4j-contrib/spatial/blob/df8d737d1a2e6821e19087efd2f3350aacd4eab6/.travis.yml#L2-L4

to "openjdk8" as Oracle is no longer available in the default/current build images due to EOL / Paid maintainance

**Comment by stevenleadbeater** [comment]
> openjdk8

done

**Comment by stevenleadbeater** [comment]
I've had to fix some further issues on this, it appears as though GeoServer now loads the database location in as a URI which was confusing the location of the database on disk. This is now resolved and I have loaded up layers from the TestDynamicLayers class in GeoServer and successfully previewed them as OSM

**Comment by stevenleadbeater** [comment]
fixes #275

**Comment by craigtaverner** [comment]
Hi Steven. Thanks for this great contribution. I'd love to review and merge it, but we need to handle a tiny bit of paperwork first. Have you signed the CLA agreement described at https://neo4j.com/developer/cla/. It is a simple IP sharing agreement that we require to accept contributions. Normally it simply involves sending an email, so read the above link and send the email. Then I can look at merging this PR.

**Comment by stevenleadbeater** [comment]
Thanks @craigtaverner , I've sent the email

**Comment by craigtaverner** [comment]
Hi @stevenleadbeater, I've not seen the email yet. Can you verify that you sent it to the right address?

**Comment by stevenleadbeater** [comment]
I sent it to cla@neotechnology.com, is that not right? @craigtaverner

**Comment by craigtaverner** [comment]
That should have worked, and I see emails to that address working as recently as last week. Can you perhaps retry to cla@neo4j.com instead? That is the current official address.

**Comment by stevenleadbeater** [comment]
Thanks @craigtaverner  I've sent that through

**Comment by craigtaverner** [comment]
This is strange. I've received cla emails as recently as an hour ago, but nothing from you. I'll check with others at this end to see what is happening. In the meantime, can you join neo4j-users.slack.com so we can DM and discuss how to resolve this. I think github issue comments are not the right forum for that.

**Comment by Andy2003** [comment]
We are already on geotools `30.2` see also: https://github.com/neo4j-contrib/spatial/pull/399

**Pull request closed without merging**
