### PR TITLE
Added spatial methods for Cypher

### PR DESCRIPTION
**Pull request by RobertBierbauer**
I added some spatial methods for Cypher, which I use in my project. I wrote this methods due to the missing operations, which are comparable to PostGIS's ST_Line_Locate_Point, ST_X, ST_Y and others.
Additionally a method was added to encode the geometry property of all nodes from a WKB String to a Byte[].
I hope the methods are useful and I would be happy to get some feedback.

### CODE REVIEW

**Comment by craigtaverner** [comment]
I'd like to review this. But before we can consider it for inclusion, could you please sign the CLA (just an email) as described at http://neo4j.com/docs/stable/cla.html, and let me know.

**Comment by craigtaverner** [comment]
I've done a brief initial review and while this is very interesting code that clearly does a few useful things, I do have a few issues with including it in Neo4j Spatial:

* There are no unit tests. These are important to clarify that the functions perform as expected with expected input and unexpected input.
* The functions are hard-coded to a few domain specific situations. For example:
  * You always re-project from WGS84 to web-mercator. This is probably common in many apps, but is not generic. For example: https://github.com/RobertBierbauer/spatial/blob/Enhanced-Functionality/src/main/java/org/neo4j/gis/spatial/indexprovider/LayerNodeIndex.java#L319
  * You use some domain specific model code. Like https://github.com/RobertBierbauer/spatial/blob/Enhanced-Functionality/src/main/java/org/neo4j/gis/spatial/indexprovider/LayerNodeIndex.java#L313 and https://github.com/RobertBierbauer/spatial/blob/Enhanced-Functionality/src/main/java/org/neo4j/gis/spatial/indexprovider/LayerNodeIndex.java#L338 and https://github.com/RobertBierbauer/spatial/blob/Enhanced-Functionality/src/main/java/org/neo4j/gis/spatial/indexprovider/LayerNodeIndex.java#L381 and many more.
* The other functions we had mostly used the GeoPipeline to achieve some streaming results and also encapsulate the capabilities in a better way. You code does the work directly in LayerNodeIndex and does it eagerly, creating ArrayList of results.

So in general it seems like your code is a great first draft, but would need some generalisation, unit and acceptance tests and refinement to be included. Are you interested in doing that? Do you need additional advice or support for this?

**Comment by RobertBierbauer** [comment]
Thank you for your feedback. I already thought that some generalisation is necessary. I will take a look if I can generalise the code in a way, that it is useful to me and you.

**Comment by jexp** [comment]
No activity since 2015. @RobertBierbauer do you want to look into this again addressing @craigtaverner's concerns or shall we close it?

**Comment by craigtaverner** [comment]
I had a quick look at the PR after the additional commits that were made following my earlier comments. And I see improvements, but not all. Mainly, however, this is appropriate to the LayerNodeIndex exposed via Cypher `START`. We have removed that since we started supporting procedures. I think this work could be ported into procedures, but not used as is.

**Comment by RobertBierbauer** [comment]
Sorry, I forgot about this Pull Request. I do not intend to adjust my code anymore, so feel free to decline this PR.

**Comment by craigtaverner** [comment]
Thanks @RobertBierbauer. I've taken note of the idea, and will see if it is feasible to code things like ST_Line_Locate_Point in procedures for Neo4j 3.x.

**Pull request closed without merging**
