### PR TITLE
Migrate Geotools from 14.4 to 21.0

### PR DESCRIPTION
**Pull request by deniger**
+ Migrate Geotools from 14.4 to 21.0
+ Fix 2 unit tests by using Locale.ENGLISH to format number and thow exception if file doesn't exist

### CODE REVIEW

**Comment by deniger** [comment]
Hello, any news about this PR ?

**Comment by mprins** [comment]
final/last release of geotools 21.x is this week, would be better to upgrade this PR to a currently active release of geotools, see also: https://github.com/geoserver/geoserver/wiki/Release-Schedule

**Comment by stevenleadbeater** [comment]
@mprins this PR was originally raised in April. Moving from 21 to 22.x is pretty trivial by comparison to what has been done in this PR. Can this be merged and followed up with a subsequent patch to the next major increment of GeoServer?

**Comment by Andy2003** [comment]
We are already on geotools `30.2` see also: https://github.com/neo4j-contrib/spatial/pull/399

**Pull request closed without merging**
